main:
  - name: Home
    url: /
    weight: 10
  - name: CV
    url: /uploads/Pedro_Abelin__CV.pdf
    weight: 20
  - name: Research
    url: research/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 40
  - name: Contact
    url: contact/
    weight: 50
