main:
  - name: Home
    url: /
    weight: 10

  - name: CV
    url: "https://pedroabelin.com/uploads/Pedro_Abelin__CV.pdf"
    weight: 20

  - name: Research
    url: /research/
    weight: 30

  - name: Teaching
    url: /teaching/
    weight: 40

  - name: Media
    url: /media/
    weight: 45

  - name: Writing
    url: /writing/
    weight: 50
